import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { AlertProvider } from "@/components/alert/alertProvider";

export const metadata: Metadata = {
  title: "LuvWish",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <AlertProvider>
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </AlertProvider>
      </body>
    </html>
  );
}
